### ISSUE TITLE
Remove indir dependencies 

### ISSUE THREAD

**Issue by melodiemonod** [MLGlobalHealth/phyloSI-RakaiAgeGender#11]
Hi @abriz97!

https://github.com/MLGlobalHealth/phyloSI-RakaiAgeGender/blob/main/src/phylo_pipeline/plots/get_doi_tsi_plots.R

Could you remove all indir.* dependencies such that the files only loads datasets from zonodo?

e.g., like in https://github.com/MLGlobalHealth/phyloSI-RakaiAgeGender/blob/main/src/surveillance_pipeline/plots/plot_eligible_participant.R

Many thanks!

**Comment by abriz97** [comment]
Thanks for pointing this out. Issue is solved, even though plot is not reproducible by everyone as it calls confidential data.
