### ISSUE TITLE
draw rds file not on zenodo

### ISSUE THREAD

**Issue by abriz97** [MLGlobalHealth/phyloSI-RakaiAgeGender#16]
The file `file.treatment.cascade.prop.participants.samples` below is currently not available on zenodo, although they should have been obtained on `get_treatment_cascade_participants.R`. 
This is weird because the other file obtained in the script is available.

@ShozenD or @melodiemonod: is it possible that this was not pushed? 
(sorry if I tag both but not sure who is the knowledgeable one here)

```{r bug}
c(
    file.treatment.cascade.prop.participants.samples, 
    file.treatment.cascade.prop.participants
) |> file.exists()
# [1] FALSE  TRUE
```

**Comment by melodiemonod** [comment]
this is on me. Just added it. Sorry for any inconvenience
