### ISSUE TITLE
remove jcolours

### ISSUE THREAD

**Issue by olli0601** [MLGlobalHealth/phyloSI-RakaiAgeGender#7]
Hi @melodiemonod 

jcolors was removed from CRAN, which makes it hard to install it, https://cran.r-project.org/web/packages/jcolors/index.html

Do we really need it and could we find a workaround?

FYI @ShozenD 

Thx olli

**Comment by melodiemonod** [comment]
Done https://github.com/MLGlobalHealth/phyloSI-RakaiAgeGender/commit/9d3f1f9d4cc1b4abd3e97b359c3059449bb96874
